### PR TITLE
Fix no-unused-vars for variables assigned to in template but only used in script

### LINKED ISSUE #64: Variable wrongly labeled as unused
It seems like there is some issue with variables being wrongly labeled as "unused" when their value is modified in an inline handler on a DOM node.

Minimal Example:
```
<script>
    let test = 0;
    function action() {
        console.log(test);
    }
</script>

<div>
    <div on:click={()=>test=1}></div>
    <div on:click={action}></div>)
</div>
```

Output:
Error: 'test' is assigned a value but never used

Used versions:
```
"devDependencies": {
    "eslint": "^7.2.0",
    "eslint-plugin-jsdoc": "^27.0.7",
    "eslint-plugin-svelte3": "^2.7.3",
    "svelte": "^3.23.2"
  }
```

Seems like no matter what happens in the <script> part, 'test' is always detected as unused.

### PR DESCRIPTION
**Pull request by Conduitry**
Fixes #64.

It's been a while since I looked at this code though, and I want to let this sit for a bit before merging, so I can be more sure this is how I want to handle this.

### CODE REVIEW

**Comment by Conduitry** [comment]
Hm the test failure is because this lists `eslint@>=6.0.0` as a devdep, and ESLint 7 no longer works on Node 8. I'd rather not just drop Node 8 from the support/testing matrix. I guess I'll sit on this decision as well.

**Comment by benmccann** [comment]
For what it's worth, Node 8 is no longer supported: https://nodejs.org/en/about/releases/

**Comment by NicoCevallos** [comment]
@Conduitry check what I did in the file `.github/workflows/ci.yml` in this PR https://github.com/sveltejs/eslint-plugin-svelte3/pull/62 to remote test over Node 8 and adding version 14

**Comment by benmccann** [comment]
I think @Conduitry knows how to update `ci.yml`. The question is whether we should as was stated:

> I'd rather not just drop Node 8 from the support/testing matrix.

Something else I found out recently is that I believe Sapper (or at least the Sapper template) won't even run on Node 10 anymore. Of course that's Sapper and not Svelte, but I think the ship has sailed on Node 8, which is now unsupported

**Comment by NicoCevallos** [comment]
Sure, I didn't want to offend anybody with my comment...

Another option could be to publish one version to support newer versions of Node and ESLint, and another to continue supporting Node 8 if it's required. In my comment I mentioned what I did to don't break Node 8 tests, but that limits to install only ESLint 6.x.x

**Comment by benmccann** [comment]
Another data point on this, Rollup requires Node 10 to run and the next version of Webpack will as well

**Comment by benmccann** [comment]
`rollup-plugin-svelte` now also requires Node 10, so I'm not sure there's any benefit of keeping Node 8 support at this point. What do you think @Conduitry ?

**Comment by benmccann** [comment]
Node 8 support was dropped in https://github.com/sveltejs/eslint-plugin-svelte3/pull/77, so hopefully the tests should pass if you rebase this

**Pull request merged**
