### PR TITLE
Use TS 4.5 `preserveValueImports` if it's available

### LINKED ISSUE #154: Support using TypeScript 4.5 `preserveValueImports`
Currently, this plugin uses a TS transformer to effectively accomplish what `preserveValueImports: true` does. Unfortunately, usage of this transformer is not harmless because it breaks the new `import { foo, type bar } from "foo"` inline type imports.

As far as I can tell, the best way to handle this is to check the TypeScript version that was given to `eslint-plugin-svelte3`. If it's 4.5 or greater, set `preserveValueImports: true` in the inline TypeScript config, and do not provide the current transformer. Otherwise, do as the plugin currently does.

### PR DESCRIPTION
**Pull request by Monkatraz**
Fixes #154
Closes #142 

I also updated the package's dev-dependencies to use the latest TypeScript stuff. I did this so that I could add a test for checking if the inline type import syntax works.

### CODE REVIEW

**Comment by Monkatraz** [comment]
It appears I need to rewrite the test runner... ESLint doesn't seem to support that synchronous API anymore.

**Comment by Monkatraz** [comment]
Okay, done. Supporting old Node is a pain, man.

Closes #142

**Comment by dummdidumm** [comment]
Could you explain what is the difference to #142 with regards to the eslint bump? For example why is the `exists` function in there instead if the node `existsSync` and why only use eslint<8 ?

**Comment by Monkatraz** [comment]
My memory is already fuzzy lol but I'm pretty sure `existsSync` is deprecated.

With the ESLint versioning, it has to do with the supported Node versions. Tests will fail with ESLint 8 because it's not compatible.

**Review by dummdidumm — APPROVED** [review]

**Pull request merged**
