### PR TITLE
Drop Node 10 and 12. Upgrade to eslint 8

### PR DESCRIPTION
**Pull request by benmccann**
ref https://github.com/sveltejs/kit/pull/4553

### CODE REVIEW

**Review by dummdidumm — APPROVED** [review]

**Comment by Conduitry** [comment]
@benmccann @dummdidumm Do you think we also want to bump the peerdep of ESLint to 8+? I would _think_ so, but I wanted to get other opinions, since it wasn't included in this PR.

**Comment by benmccann** [comment]
I don't have much of an opinion one way or the other. The one thing to possibly check would be whether eslint 8 is compatible with older versions of Node and would run on sveltejs/svelte repo if there's a concern about being able to run the latest version of this plugin on that repo

**Comment by benmccann** [comment]
I just bumped the peerdep version. I sent https://github.com/sveltejs/svelte/pull/7506 which shows eslint 8 works just fine on older versions of node.

I also noticed the `engines` field present in this package and removed it. Saying we support Node 10 was no longer accurate, but making it Node 14 seemed like it could be unnecessarily annoying since this package does actually work on Node 10 and 12 as far as I'm aware

**Comment by Conduitry** [comment]
If we're saying the peerdep is ESLint 8+ then I suppose we also automatically inherit its engines requirement. As long as this plugin works wherever the underlying ESLint versions we support work, I think we're good there.

**Comment by Conduitry** [comment]
And I just added Node 18 to the CI matrix. I think this is ready to go. I'll merge it, and then release 4.0.0.

**Pull request merged**
