### PR TITLE
Fix TS validation errors and missing imports

### PR DESCRIPTION
**Pull request by Monkatraz**
Uses [a TS transformer from `svelte-preprocess`.](https://github.com/sveltejs/svelte-preprocess/blob/8c14f5d34229735b8f39acd339e6cd4a3350197d/src/transformers/typescript.ts#L35)

Linting TypeScript could fail (often easily) due to two factors:
* TypeScript handles imports in a way that often means they are removed from the compiled code
* The second compilation of the Svelte source was with blanked scripts, meaning that it would throw a `ValidationError` due to undeclared variables

Both issues have been fixed. The first issue was fixed by using the previously mentioned TypeScript transformer from `svelte-preprocess`, which correctly preserves imports and does not adjust them.

The latter issue was fixed by using `compile.parse` instead of a full recompilation. We only need the AST at this point in the code, which is exactly what `compile.parse` was meant for.

Additionally, I made it so that if the compiler threw an error, the error would be correctly mapped back to the source file.

Fixes https://github.com/sveltejs/eslint-plugin-svelte3/issues/86
Fixes https://github.com/sveltejs/eslint-plugin-svelte3/issues/85

### CODE REVIEW

**Comment by dummdidumm** [comment]
Good catch, thanks! Could you add a test case that would fail without these changes?

**Comment by Monkatraz** [comment]
Aight, tests added.

**Comment by dummdidumm** [comment]
I just realized that the ts/js paths are completely separate now, which means the function could be reordered for better readability. Doesn't have to be part of this PR though.

**Comment by Conduitry** [comment]
Right now I'm more concerned about the `Error: ESLint configuration of processor in 'samples/.eslintrc.js#overrides[0]' is invalid: 'svelte3/svelte3' was not found.` though. The filename case change is all I had to do to get the tests passing locally for me, and I have no idea what the failure in CI is.

**Comment by Conduitry** [comment]
Oh, ah ha! I'm able to reproduce that error locally now. It appears to only happen on Node 10 and 12 and not 14.

**Comment by Conduitry** [comment]
I have absolutely _no_ idea why that error message is what was being produced, but the issue was from attempting to use the optional chaining operator, which is unsupported in Node 10 and Node 12.

**Comment by Monkatraz** [comment]
> I have absolutely _no_ idea why that error message is what was being produced, but the issue was from attempting to use the optional chaining operator, which is unsupported in Node 10 and Node 12.

That explains it...

That error was so awful I thought the CI tests failing wasn't actually my PR!

**Comment by Conduitry** [comment]
Yeah, I dunno. Presumably ESLint is trying to `require()` the plugin, and when it fails with a parsing error, that error gets completely swallowed and it's just reported as "your configuration is invalid because it refers to a plugin which doesn't exist", which is less than helpful.

**Comment by Conduitry** [comment]
This has been released in 3.1.1. Thank you for the PR!

**Pull request merged**
