### PR TITLE
fix error. Could not find ESLint Linter in require cache

### PR DESCRIPTION
**Pull request by muhajirdev**
Hey, 
I am not entirely sure actually. Whether this is the right fix or not. 

I was trying to use it with VSCode . I got error ` Could not find ESLint Linter in require cache`. And then I tried to trace it back the the `node_modules`. Changing this lines helps removing the error. Not sure if it's the right thing to do :)

### CODE REVIEW

**Comment by frederikhors** [comment]
Are you using eslint 6?

**Comment by Conduitry** [comment]
Looks like yeah ESLint 6 changed some paths around. Thanks for catching this, I think I'm going to use a different solution though.

**Comment by frederikhors** [comment]
> I think I'm going to use a different solution though.

Or we can fix, no?

**Comment by Conduitry** [comment]
There seems to be quite a bit more that's changes besides these paths. Some of the other changes in ESLint 6 look like they might make a few more things possible without resorting to the awful hacks used in this plugin, but it does mean that getting this working isn't as simple as updating how we find the Linter class in the require cache.

**Comment by paulomanrique** [comment]
I'm getting the exact same error on Eslint 5.3.0. My package.json:

```json
{
  "devDependencies": {
    "eslint": "^5.3.0",
    "eslint-config-airbnb-base": "^13.2.0",
    "eslint-plugin-import": "^2.17.2",
    "eslint-plugin-svelte3": "^2.7.1",
    "npm-run-all": "^4.1.5",
    "rollup": "^1.12.0",
    "rollup-plugin-commonjs": "^10.0.0",
    "rollup-plugin-livereload": "^1.0.0",
    "rollup-plugin-node-resolve": "^5.2.0",
    "rollup-plugin-svelte": "^5.0.3",
    "rollup-plugin-terser": "^4.0.4",
    "svelte": "^3.2.0"
  }
}

```

**Comment by Conduitry** [comment]
What version of this plugin are you using? v2 only supports ESLint 6.

**Comment by paulomanrique** [comment]
Oh you're right, I'm using ESLint v5 because of the Airbnb base which still doesn't support. I guess I'll have to use another pattern then...

**Pull request closed without merging**
