### PR TITLE
[chore] Deprecate this repository

### PR DESCRIPTION
**Pull request by baseballyama**
Now our official ESLint plugin is [eslint-plugin-svelte](https://github.com/sveltejs/eslint-plugin-svelte).

### CODE REVIEW

**Comment by baseballyama** [comment]
Oh CI is failed. I will fix this.

**Comment by baseballyama** [comment]
I created PR https://github.com/sveltejs/eslint-plugin-svelte3/pull/205 for fixing tests.

**Comment by dummdidumm** [comment]
Nice! We should also open a PR at the new official plugin to remove the wording that it's not official. Then we can merge both at once.

**Review by dummdidumm — APPROVED** [review]
🎉

**Pull request merged**
