### PR TITLE
Consider @typescript-eslint's rules for invalid messages

### PR DESCRIPTION
**Pull request by Sxxov**
Currently when using the `@typescript-eslint` plugin, there are some parts where they some rules apply unnecessarily.
I found it's because I'm using some their alternative rules, which are enabled under a namespace (eg. `@typescript-eslint/indent`), and thus not properly marked as invalid when post-processing.

Before: 
image

After:
image

### CODE REVIEW

**Comment by Sxxov** [comment]
Something notable with this how it's different from #98. This fixes the internal checking and enables users to use the rules instead of disabling them.

**Comment by dummdidumm** [comment]
Not sure what you mean by the "how it's different from #98" sentence, you both change the same line for the one rule - you add one more though. Could you add a test that checks that these new false positives are filtered out? Thanks!

**Comment by Sxxov** [comment]
@dummdidumm 

> Not sure what you mean by the "how it's different from #98" sentence, you both change the same line for the one rule - you add one more though. 

Ah, that's very much my bad. I read template and thought he meant like code templates (doh).

> Could you add a test that checks that these new false positives are filtered out? Thanks!

Yep, give me a bit

**Review by dummdidumm — APPROVED** [review]

**Comment by Conduitry** [comment]
This has been released in 3.2.0 - thanks!

**Pull request merged**
