### PR TITLE
Remove extra newlines from undented code

### PR DESCRIPTION
**Pull request by jarrodldavis**
When using `eslint-plugin-prettier` with this plugin, Prettier reports some extra newlines in script blocks. This updates the preprocessing logic to remove those newlines from the code string given to ESLint.  

- Track and skip over the first line if it's empty (as is typical for code strings extracted from `<script>` blocks)
- Prevent extra newlines from being added between different code sections (such as between the module and instance scripts, or before trailing variable references

### CODE REVIEW

**Comment by Conduitry** [comment]
Hi, thanks for the PR! I tried this branch out with `eslint-plugin-prettier` and I ran into some issues with the eslint/prettier fixes for problems not being mapped back to the correct locations in the file. There also seemed to be some issues with Prettier attempting to format the code that gets injected at the beginning and end of the file to keep eslint happy about variable declarations and references.

So I tried approaching this from another angle, which is in the [`prettier-fixes` branch](https://github.com/sveltejs/eslint-plugin-svelte3/tree/prettier-fixes). Can you try this out and see whether it does what you need it to do? I'd never used `eslint-plugin-prettier` previously, so I could be missing something.

**Comment by jarrodldavis** [comment]
Interesting, I actually ran into some mapping issues when I was starting to implement them and I thought I fixed them. 

Could you show me the Svelte template you ran my branch against? I used the [sapper v3 template for rollup] as a base, and you can see the linting setup I configured [here]:

[sapper v3 template for rollup]: https://github.com/sveltejs/sapper-template/tree/rollup-v3
[here]: https://github.com/jarrodldavis/sapper-template

**Comment by jarrodldavis** [comment]
Also, I ran your branch against my template repo and it appears to be ignoring any truly empty lines at the beginning or end of the `<script>` block, e.g.:

```html
<script>

  import Nav from "../components/Nav.html";

  export let segment;
  
</script>
```

**Comment by jarrodldavis** [comment]
I'm going to go ahead and close this since it's a complicated problem and it seems better to only use Prettier by itself instead of within another linter, especially when dealing with embedded/extracted code.

**Pull request closed without merging**
