### PR TITLE
should ignore `@typescript-eslint/indent` in template

### PR DESCRIPTION
**Pull request by meowtec**

### CODE REVIEW

**Comment by dummdidumm** [comment]
Could you provide a short explanation why this is needed and add a test case that confirms the new behavior?

**Comment by meowtec** [comment]
> Could you provide a short explanation why this is needed and add a test case that confirms the new behavior?

When we using `@typescript-eslint`, we usually disable `indent` and enable `@typescript-eslint/indent`.

```
indent: 0,
'@typescript-eslint/indent': ['error', 'tab'],
```

Now ESLint is not working as expected:
```
<div>{some expression}</div>
          ~~~~~~~~~~~~~
          Expected indentation of 2 spaces but found 0.eslint@typescript-eslint/indent
```

**Comment by meowtec** [comment]
Test case added.

The CI broken, I don't know why but I think is not my fault.

**Review by dummdidumm — APPROVED** [review]

**Comment by meowtec** [comment]
CI failed because of svelte@3.35

**Comment by dummdidumm** [comment]
Superseeded by #101 . Still thanks for your contribution!

**Comment by Conduitry** [comment]
#101 has been released in 3.2.0.

**Pull request closed without merging**
